import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  DxDataGridModule,
  DxFormModule,
  DxButtonModule,
  DxCheckBoxModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxDateBoxModule,
  DxNumberBoxModule,
  DxLoadPanelModule,
  DxPopupModule,
  DxScrollViewModule,
  DxToolbarModule,
  DxTabsModule,
  DxListModule,
  DxMenuModule,
  DxDropDownButtonModule,
} from 'devextreme-angular';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    DxDataGridModule,
    DxFormModule,
    DxButtonModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxDateBoxModule,
    DxNumberBoxModule,
    DxLoadPanelModule,
    DxPopupModule,
    DxScrollViewModule,
    DxToolbarModule,
    DxTabsModule,
    DxListModule,
    DxMenuModule,
    DxDropDownButtonModule,
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    DxDataGridModule,
    DxFormModule,
    DxButtonModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxDateBoxModule,
    DxNumberBoxModule,
    DxLoadPanelModule,
    DxPopupModule,
    DxScrollViewModule,
    DxToolbarModule,
    DxTabsModule,
    DxListModule,
    DxMenuModule,
    DxDropDownButtonModule,
  ],
})
export class SharedModule {}
