import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import {
  DxDataGridModule,
  DxFormModule,
  DxButtonModule,
  DxCheckBoxModule,
  DxSelectBoxModule,
  DxTextBoxModule,
  DxDateBoxModule,
  DxNumberBoxModule,
  DxLoadPanelModule,
  DxPopupModule,
  DxScrollViewModule,
  DxToolbarModule,
  DxTabsModule,
  DxListModule,
  DxMenuModule,
  DxDropDownButtonModule,
  DxFileUploaderModule,
} from 'devextreme-angular';
import { FileDropzoneComponent } from '../components/file-dropzone/file-dropzone.component';

const commonComponents = [FileDropzoneComponent];
@NgModule({
  declarations: [...commonComponents],
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    DxDataGridModule,
    DxFormModule,
    DxButtonModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxDateBoxModule,
    DxNumberBoxModule,
    DxLoadPanelModule,
    DxPopupModule,
    DxScrollViewModule,
    DxToolbarModule,
    DxTabsModule,
    DxListModule,
    DxMenuModule,
    DxDropDownButtonModule,
    DxFileUploaderModule,
  ],
  exports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    DxDataGridModule,
    DxFormModule,
    DxButtonModule,
    DxCheckBoxModule,
    DxSelectBoxModule,
    DxTextBoxModule,
    DxDateBoxModule,
    DxNumberBoxModule,
    DxLoadPanelModule,
    DxPopupModule,
    DxScrollViewModule,
    DxToolbarModule,
    DxTabsModule,
    DxListModule,
    DxMenuModule,
    DxDropDownButtonModule,
    DxFileUploaderModule,
    ...commonComponents,
  ],
})
export class SharedModule {}
